### ISSUE TITLE
400 Error for app behind nginx 

### ISSUE THREAD

**Issue by tfmm** [oauth2-proxy/oauth2-proxy#2362]
I have an application setup using Nginx forward-auth, with the oauth proxy also behind nginx.  Proxy directs correctly to the OIDC login, however after completing the login flow, all I get is a `400 Bad Request` error. 

## Expected Behavior

Redirection to application after auth. 

## Current Behavior

400 error instead of proper redirection

## Possible Solution

I honestly have no idea.

## Steps to Reproduce (for bugs)

NGINX setup for host to authenticate:
```
        location / {
             expires -1;

             error_page 401 = /oauth2/sign_in?rd=$scheme://$host$request_uri;
             auth_request_set $user  $upstream_http_x_auth_request_user;
             auth_request_set $token  $upstream_http_x_auth_request_access_token;
             auth_request_set $auth_cookie $upstream_http_set_cookie;
             proxy_set_header X-User  $user;
             proxy_set_header X-Access-Token $token;
             add_header Set-Cookie $auth_cookie;

             proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-Proto $scheme;
             auth_request /oauth2/auth;
        }

        location /oauth2 {
            expires -1;
            proxy_set_header Host       oauth2proxy.example.com;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Auth-Request-Redirect $request_uri;
            proxy_pass http://x.x.x.x:4180;
        }

        location = /oauth2/sign_out {
            expires -1;
            proxy_set_header Host       oauth2proxy.example.com;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Auth-Request-Redirect /oauth2/sign_in;
            proxy_pass http://x.x.x.x:4180;
        }
```

proxy config: 
```
provider = "oidc"
#user_id_claim = "sub" #uses the subject as ID instead of the email
provider_display_name = "SSO"
redirect_url = "https://oauth2proxy.example.com/oauth2/callback"
oidc_issuer_url = "https://sso.example.com"
upstreams = "https://oauth2proxy.example.com"
email_domains = [ "*" ]
cookie_domains = [".example.com"]
whitelist_domains = [".example.com"]
client_id = "SOME_CLIENT_ID"
client_secret = "SOME_CLIENT_SECRET"
pass_access_token = true
cookie_secret = "COOKIE_SECRET"
skip_provider_button = true
cookie_secure = true 
http_address = "0.0.0.0:4180" 
scope = "openid profile email users"
reverse_proxy = true
ssl_insecure_skip_verify = true
insecure_oidc_allow_unverified_email = true
```

The Issue is Zitadel, OIDC.

1.  Setup nginx and oauth2proxy with above configs
2.  visit url of host 
3.  proceed through auth flow
4.  receive 400 error

## Your Environment

Everything is in Docker, NGINX is actually NGINX Proxy Manager. `oauth2proxy.example.com` is resolvable from inside and outside network, and points to nginx proxy manager and proxies requests to the oauth2 proxy container. 

- Version used:
7.5.1

**Comment by dexter0195** [comment]
I was dealing with the exact same issue yesterday. I was able to go through the authentication flow and have the cookie set in my browser but then Nginx was replying with a 400. My issue was that the cookie was too big (the user I was testing from was part of 52 groups on Azure AD). I added the redis as recommended in the doc and the issue was fixed. 
There is also an alternative approach but that doesn't work all the time, which is to leverage the `proxy_buffers` to something like this: 
```
server {
 proxy_busy_buffers_size   512k;
 proxy_buffers   4 512k;
 proxy_buffer_size   256k;
 # rest of the nginx config below #
}
```

**Comment by tfmm** [comment]
Thanks, I setup redis after seeing this message, and still seeing the same problem unfortunately.

**Comment by LeVraiRoiDHyrule** [comment]
> Thanks, I setup redis after seeing this message, and still seeing the same problem unfortunately.

Hi, I am trying to set oauth2-proxy with Zitadel and forward_auth too, but with Caddy. I am very interested in your setup. So far, I've set it this way:
```
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_REDIRECT_URL=https://radarr.${DOMAIN}/oauth2/callback
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://auth.${DOMAIN}
      - OAUTH2_PROXY_WHITELIST_DOMAIN=.${DOMAIN}
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR=true
      - OAUTH2_PROXY_CLIENT_ID=${RADARR_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=dummy #${RADARR_CLIENT_SECRET}
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      #- OAUTH2_PROXY_OIDC_GROUPS_CLAIM=groups
      #- OAUTH2_PROXY_SCOPE="openid profile email groups"
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
```

But I am having a 401 Unauthorized error, would you know what I've set up wrong ?

**Comment by nnelson1601** [comment]
> Thanks, I setup redis after seeing this message, and still seeing the same problem unfortunately.

I'm also running into a 400 error from my nginx service as well.  I have redis configured, and I can see that it is being populated with cookie data.  

@tfmm Were you able to to sort out the issue on your end?

**Comment by tfmm** [comment]
I never was able to sort the issue when using Nginx Proxy Manager.  I've since moved to raw nginx and things are working fine.

**Comment by thebigbone** [comment]
@tfmm I am also having some difficulties with running oauth2proxy behind nginx. Would you be able to paste the nginx config for your oauth2proxy instance itself? I would really appreciate it!

**Comment by tfmm** [comment]
Here's the relevant files.

Virtual Server: 
```
# ------------------------------------------------------------
# oauth2proxy.example.com
# ------------------------------------------------------------

server {
  set $forward_scheme http;
  set $server         "oauth2proxy_url";
  set $port           port_number;

  listen 80;
  listen [::]:80;

  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;

  server_name oauth2proxy.example.com;

  # Let's Encrypt SSL
  ssl_certificate /data/lecerts/live/example.com/fullchain.pem;
  ssl_certificate_key /data/lecerts/live/example.com/privkey.pem;

  # Force SSL
  include conf.d/include/force-ssl.conf;

  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
  proxy_http_version 1.1;

  access_log /data/logs/oauth2proxy_access.log combined;
  error_log /data/logs/oauth2proxy_error.log error;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_pass       http://oauth2proxy_url:port_number;
    
    # Force SSL
    include conf.d/include/force-ssl.conf;
    
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_connect_timeout 1;
    proxy_send_timeout 30;
    proxy_read_timeout 30;
  }

  # Custom
  include conf.d/include/server_proxy[.]conf;
}
```

force-ssl.conf:
```
if ($scheme = "http") {
	return 301 https://$host$request_uri;
}
```

server_proxy.conf: 
```
proxy_headers_hash_max_size 512;
proxy_headers_hash_bucket_size 128;
location = /oauth2/auth {
    internal;
    proxy_pass http://oauth2proxy_url:port_number;
    proxy_set_header Host             $host;
    proxy_set_header X-Real-IP        $remote_addr;
    proxy_set_header X-Scheme         $scheme;
       
    # nginx auth_request includes headers but not body
    proxy_set_header Content-Length   "";
    proxy_pass_request_body           off;
}
location /oauth2/ {
    proxy_pass http://oauth2proxy_url:port_number;
    proxy_set_header Host                    $host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Scheme                $scheme;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
    
}

location = /oauth2/sign_out {
    # Sign-out mutates the session, only allow POST requests
    if ($request_method != POST) {
        return 405;
    }

    proxy_pass http://oauth2proxy_url:port_number;
    proxy_set_header Host                    $host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Scheme                $scheme;
}
```

**Comment by thebigbone** [comment]
> Here's the relevant files.
> 
> Virtual Server:
> 

Thanks. But it seems like you're using the internal IP of oauth instance instead of using the domain name directly, which is what I am trying to do. Have you tried using the oauth instance for a service from a different server by passing in just the domain?

**Comment by tfmm** [comment]
I'm not sure what you mean, this provided config is for the virtual server for the oauth proxy itself, you should be able to use a hostname or IP in place of `oauthproxy2_url`

**Comment by thebigbone** [comment]
> I'm not sure what you mean, this provided config is for the virtual server for the oauth proxy itself, you should be able to use a hostname or IP in place of `oauthproxy2_url`

Oh yes. Apologies. I did use it but unfortunately, I still get this stupid error from the service which is behind nginx:

```
2025/04/15 19:39:07 [error] 18075#18075: *798 auth request unexpected status: 302 while sending to client, client: 223.238.230.77, server: speed-nl1.example.xyz, request: "GET / HTTP/1.1", host: "speed-nl1.example.xyz"
2025/04/15 19:40:07 [error] 18075#18075: *801 auth request unexpected status: 302 while sending to client, client: 223.238.230.77, server: speed-nl1.example.xyz, request: "GET / HTTP/1.1", host: "speed-nl1.example.xyz"
```

**Comment by thebigbone** [comment]
The config for the service:
```
server {                                                                                                                                                                                      
        server_name speed-nl1.example.xyz;                                                                                                                                                       
        set $speednl1 127.0.0.1;                                                                                                                                                              
                                                                                                                                                                                              
        location / {                                                                                                                                                                          
                auth_request /oauth2/auth;                                                                                                                                                    
                error_page 401 = /oauth2/sign_in;                                                                                                                                             
                proxy_set_header Host $host;                                                                                                                                                  
                proxy_set_header X-Real-IP $remote_addr;                                                                                                                                      
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;                                                                                                                  
                proxy_set_header X-Forwarded-Proto $scheme;                                                                                                                                   
                proxy_set_header X-Forwarded-Protocol $scheme;                                                                                                                                
                proxy_set_header X-Forwarded-Host $http_host;                                  
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_pass http://$speednl1:8043;
        }                                       

        location /oauth2/ {
                proxy_pass       https://oauth-user.example.xyz;
                proxy_set_header Host                    $host;
                proxy_set_header X-Real-IP               $remote_addr;
                proxy_set_header X-Auth-Request-Redirect $request_uri;
        }                                       

        location = /oauth2/auth {
                proxy_pass       https://oauth-user.example.xyz;
                proxy_set_header Host             $host;
                proxy_set_header X-Real-IP        $remote_addr;
                proxy_set_header X-Forwarded-Uri  $request_uri;
                proxy_set_header Content-Length   "";
                proxy_pass_request_body           off;
        }  
```

**Comment by thebigbone** [comment]
> I'm not sure what you mean, this provided config is for the virtual server for the oauth proxy itself, you should be able to use a hostname or IP in place of `oauthproxy2_url`

To be clear, I was asking if you're able to access the instance directly from `oauth2proxy.example.com`

**Comment by thebigbone** [comment]
After fiddling around, I am now getting the same 404 error. Did you solve it by any chance:
```
2025/04/15 20:00:31 [error] 18437#18437: *1 auth request unexpected status: 404 while sending to client, client: 223.238.230.77, server: speed-nl1.example.xyz, request: "GET / HTTP/1.1", host: "speed-nl1.example.xyz"
```

**Comment by thebigbone** [comment]
> > To be clear, I was asking if you're able to access the instance directly from `oauth2proxy.example.com` from a different server outside the network behind nginx without any issues
> 
> Yes, I have no issues using it off-network.

Do you have the same config as I pasted above for the host you're trying to protect?
