### ISSUE TITLE
Exclude oauth2-proxy's endpoints from --skip-auth-regex/--skip-auth-route

### ISSUE THREAD

**Issue by rassie** [oauth2-proxy/oauth2-proxy#979]
## Expected Behavior

My API currently only partly requires authentication. Whether a particular endpoint accepts authentication or requires it, is currently defined in code. I would like to keep it this way at least for now, so I would like to use `oauth2-proxy` to provide a JWT if a user is authenticated, but otherwise do nothing, especially no redirects to login pages etc. I figured I could implement it like this (in `docker-compose` context): 

```
# Do not redirect to login for any requests
OAUTH2_PROXY_SKIP_AUTH_REGEX: ".*"
# Provide backwards compatibility with clients with JWTs
OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
# Forward JWT for clients with oauth2-proxy's session cookie 
OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
``` 

I'm relying on `/oauth2/userinfo` to get my user's information. 

## Current Behavior

Currently, `/oauth2/userinfo` is also subject to request filtering with `--skip-auth-regex`/`--skip-auth-route`, so that skipping every request with `.*` also disables `oauth2-proxy`'s endpoints. 

## Possible Solution

I've implemented a poor man's workaround by moving code around in `oauthproxy.go` in the `serveHTTP` function, however that can't be a solution. Possibly a check in the `isAllowedRoute` would work better. Either way, there probably should be a switch allowing to either include or exclude internal endpoints in the request filtering. 

## Your Environment

- Version used: `git` snapshot, locally compiled with the included `Dockerfile`.

**Comment by NickMeves** [comment]
If you are using `.*` for your skip auth regex, it seems like you probably don't want OAuth2-Proxy positioned inline in your architecture, but rather on the side of your web proxy like in subrequest architectures potentially?

Here are some resources:
https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-nginx-auth_request-directive

You bring up a valid point worth considering though: what is the point of doing `p.SkipAuthProxy` on any URLs under `p.ProxyPrefix` (e.g. `/oauth2/*). 🤔  -- `p.IsAllowedRequest` as the second to last stage in the switch has its merits.

If we really had URLs that conflicted with a backend URL structure -- the application could configure OAuth2-Proxy to use a different `ProxyPrefix`.

**Comment by JoelSpeed** [comment]
This does also remind me of a strange point that we have authz then authn then authz in most requests. Long term I'd prefer us to have all authn then all authz, which would mitigate this issue in some regards I believe.

The only issue with that currently is that we log when each authn fails, we don't really want to do that long term I don't think (or at least, we need levelled logging)

**Comment by rassie** [comment]
> If you are using `.*` for your skip auth regex, it seems like you probably don't want OAuth2-Proxy positioned inline in your architecture, but rather on the side of your web proxy like in subrequest architectures potentially?

Might be the case, thanks for the pointer. I'm splitting our monolithic frontend into multiple micro-frontends and need to solve the authentication story. In the monolith, I'm using [oidc-client-js](https://github.com/IdentityModel/oidc-client-js) which would require explicit configuration for each micro-frontend if kept, which is exactly why I'm looking into `oauth2-proxy` to keep the authentication "outside" of the frontends, but I'm not yet sure whether it fits all of our edge cases. Putting it in front of the backend is the first experiment of many.

But in all fairness, the issue at hand is `ProxyPrefix`ed endpoints being unavailable with some regexps, so we can safely ignore my architecture for now :) 

> You bring up a valid point worth considering though: what is the point of doing `p.SkipAuthProxy` on any URLs under `p.ProxyPrefix` (e.g. `/oauth2/*`).  -- `p.IsAllowedRequest` as the second to last stage in the switch has its merits.
> 
> If we really had URLs that conflicted with a backend URL structure -- the application could configure OAuth2-Proxy to use a different `ProxyPrefix`.

If you'd like to change the behavior unconditionally, moving `switch` clauses around might be sufficient, but with a condition doing this in `isAllowedRequest` will probably be much easier. Just my two cents :)

**Comment by NickMeves** [comment]
> If you'd like to change the behavior unconditionally, moving `switch` clauses around might be sufficient, but with a condition doing this in `isAllowedRequest` will probably be much easier. Just my two cents :)

Agreed, that is the likely fix if that is the route we deem is best. We are just very careful about breaking changes and document any of them (even minor thoroughly).

Since boundaries around allowlists for niche use cases are the most likely to result in users creating more hacky configurations outside of the norm -- I imagine any slight switches to order of operations would break existing installations in some cases.

**Comment by rassie** [comment]
@NickMeves I think this is still valid, could you reopen please?

**Comment by rassie** [comment]
@NickMeves I assume this will probably be fixed with #1128 too?

**Comment by JoelSpeed** [comment]
@rassie I think you're correct, #1128 will fix this issue

**Comment by JoelSpeed** [comment]
This should be fixed now as we have merged the PR which fixes the routing ordering

**Comment by JoelSpeed** [comment]
You're right, this isn't fixed. That said, coming back to this now, fixing it would be a breaking change in the behaviour that's been established for over 5 years. I wonder if there's a better way this can be worked, eg, using something like Nginx in front of OAuth2 Proxy to solve the issue of which paths need auth instead of having OAuth2 Proxy make those decisions

**Comment by JoelSpeed** [comment]
> Wasn't https://github.com/oauth2-proxy/oauth2-proxy/pull/1128 the breaking change that fixed this originally? I remember checking on it and being sure it does that -- is it possible that this particular issue came undone since that patch merged?

It's quite possible, did you know exactly when this change in behaviour came about, if we know it's not been long since the behavioural change it may be ok to undo it

**Comment by JoelSpeed** [comment]
Just had a quick dive in, and I think https://github.com/oauth2-proxy/oauth2-proxy/pull/1545 might have been the change that broke this

**Comment by JoelSpeed** [comment]
Yeah ok, I can see #1128 was the one that broke this, we need to change the authonly slightly to restore the behaviour, I'll work up a fix

**Comment by JoelSpeed** [comment]
On second thoughts, if I checkout the commit before #1128, the `IsAuthenticatedRequest` comes before the `AuthOnly` in the mux, which means that it was broken before #1128 🤔

**Comment by JoelSpeed** [comment]
Ok, that was a journey! 

I've gone back through the blame and discovered that actually, since we have had any form of whitelisted paths, they have always taken precedence over the `AuthOnly` paths. So this isn't a bug, but more a feature request.

I could see us supporting this with some configuration to allow users to choose the behaviour, they would be able to say, have a relaxed or strict mode, relaxed would allow the session through like the current behaviour, strict would require a session and not pass if the session was nil

https://github.com/oauth2-proxy/oauth2-proxy/commit/c4d25d271fb80a03bb97d4b668eb2e47132827be

**Comment by ZHANNARaykh** [comment]
zhanna.r29.09.84@gmail.com

**Comment by rassie** [comment]
@JoelSpeed this is still relevant and not stale. 

More on the topic: I feel like we are coming full circle and need to start from the beginning. It's probably best if I quoted @NickMeves further up in this issue 

> You bring up a valid point worth considering though: what is the point of doing `p.SkipAuthProxy` on any URLs under `p.ProxyPrefix` (e.g. `/oauth2/*`)

I think this core point is still valid. The inverse (i.e. proposed in this issue) allows for partial authentication scenarios, but I fail to see a valid reason for the status quo.

That being said, your point of being a breaking behaviour for five years is probably correct (even if I can't imagine anyone relying on relevant parts of that behaviour), but we have to keep #1128 in mind. I still can't make sense of what is happening in the gorilla mux, but I still think that patch for #1128 worked at the time (more or less confirmed [by your comment on the PR](https://github.com/oauth2-proxy/oauth2-proxy/pull/1128/files#r645970357)). Since it's not working now, we probably have a nasty situation where the supposed breaking change has been introduced in a minor version (not seen as breaking change at the time) and then reverted to previous behaviour in an unidentified commit at an unknown later point in time.

I have no idea how to resolve this correctly. I can take a stab at bisecting and finding out whether #1128 worked at the time (with regard to this issue) and if so, at which point it broke. I would nevertheless appreciate someone tackling this problem -- even if means a breaking change. After all, 8.x is long overdue :)

**Comment by JoelSpeed** [comment]
> I have no idea how to resolve this correctly. I can take a stab at bisecting and finding out whether https://github.com/oauth2-proxy/oauth2-proxy/pull/1128 worked at the time (with regard to this issue) and if so, at which point it broke. I would nevertheless appreciate someone tackling this problem -- even if means a breaking change. After all, 8.x is long overdue :)

If you have the time to dig into this a bit further and check what's going on, I have a vague memory of us breaking this, getting an issue, and then fixing it back to the original behaviour. But yes, perhaps there are some choices we can make as we approach a breaking version

**Comment by rassie** [comment]
@JoelSpeed I think we need to revisit this issue. I've made a small test with released versions of `oauth2-proxy` (7.0.1, 7.1.3, 7.2.1, 7.3.0, 7.4.0, 7.5.0 and 7.6.0) which checked the response code of `/oauth2/auth` and in all cases it's been 200/202 with `OAUTH2_PROXY_SKIP_AUTH_ROUTES` set to `.*`, while being 401 when no route skipping was involved. 

I think that the semantics of this issue changed from when I initially opened it -- I think I implied that `/oauth2/userinfo` is unusable since it returns no auth information even when signed in, this is certainly no longer the case, which could indicate that #1128 changed something for the better. However, `/oauth2/auth` still can't return a 401 if it falls under the route skip regex, so this still needs addressing.

I'll try to dig into the code for a logical explanation and maybe I'll manage to craft a fix.

**Comment by rassie** [comment]
OK, using new syntax for `--skip-auth-route`, setting `OAUTH2_PROXY_SKIP_AUTH_ROUTES` to  `!=/oauth2/.*` seems to do what is needed. Still think we need a patch, because there is probably still no use case for the status quo (i.e. `oauth2-proxy` enabled and `/oauth2/auth` being always allowed).

**Comment by JoelSpeed** [comment]
I think you are probably correct. I wouldn't expect any of the OAuth2 Proxy paths necessarily to be skipped by the skip auth routes, something we probably want to fix
